services:
  board-app:
    build: .
    container_name: board-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
    restart: unless-stopped